openapi: 3.0.3
info:
  title: Inventory service API
  version: 1.0.0
  description: |
    The **Inventory Service API** manages pictures in an inventory system.  
    It allows clients or other services to create, update, retrieve a single picture, or retrieve all pictures.  

tags:
  - name: Inventory
    description: Endpoints for managing inventory pictures

servers:
  - url: http://localhost:8080/inventory/api
    description: Local development server (for testing purposes)

paths:
  /save:
    post:
      tags:
        - Inventory
      summary: Save a new picture
      description: |
        Creates a new picture in the inventory.  
        Requires a `PictureDto` object in the request body.  
        Returns the newly saved picture.
      requestBody:
        required: true
        description: Picture data to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PictureDto'
      responses:
        '201':
          description: Picture successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Picture'
        '400':
          description: Missing or invalid parameter in the request body
        '500':
          description: Internal server error

  /{id}:
    get:
      tags:
        - Inventory
      summary: Get a picture by unique identifier (`id`)
      description: |
        Retrieves a single picture by its unique identifier (`id`).  
        Returns the picture object if found.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the picture
          schema:
            type: string
      responses:
        '200':
          description: Picture found and returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Picture'
        '400':
          description: Missing or invalid `id` parameter
        '404':
          description: Picture with the given `id` was not found
        '500':
          description: Internal server error

  /all:
    get:
      tags:
        - Inventory
      summary: Get all pictures
      description: |
        Retrieves a list of all pictures currently stored in the inventory.  
        Returns a List of picture objects.
      responses:
        '200':
          description: Successfully returned all pictures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Picture'
        '500':
          description: Internal server error

  /update/{id}:
    put:
      tags:
        - Inventory
      summary: Update an existing picture
      description: |
        Updates an existing picture in the inventory using its unique identifier (`id`).  
        Requires both the path parameter and a valid `PictureDto` in the request body.  
        Returns the updated picture.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier `id` of the picture to update
          schema:
            type: string
      requestBody:
        required: true
        description: Updated picture data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PictureDto'
      responses:
        '200':
          description: Picture successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Picture'
        '400':
          description: Invalid request body
        '404':
          description: Picture not found with the given `id`
        '500':
          description: Internal server error

components:
  schemas:
    PictureDto:
      type: object
      description: |
        Represents a picture object, without its unique identifier.
      required:
        - name
        - stock
        - price
        - description
      properties:
        name:
          type: string
          description: Title of the picture
          example: "Sunset over the mountains"
        stock:
          type: integer
          description: Number of units available in stock, it must be 0 or greater.
          example: 15
        price:
          type: number
          format: double
          description: Price of the picture. It must NOT have a negative value.
          example: 49.99
        description:
          type: string
          description: Detailed description of the picture
          example: "A beautiful high-resolution photograph of a sunset over the mountain range."
    Picture:
      type: object
      description: |
        Represents a stored picture in the inventory, including its unique identifier and full details.
      required:
        - id
        - name
        - stock
        - price
        - description
      properties:
        id:
          type: integer
          description: Unique identifier for the picture
          example: 1
        name:
          type: string
          description: Title of the picture
          example: "Sunset over the mountains"
        stock:
          type: integer
          description: Number of units available in stock, it must be 0 or greater.
          example: 15
        price:
          type: number
          format: double
          description: Price of the picture. It must NOT have a negative value.
          example: 49.99
        description:
          type: string
          description: Detailed description of the picture
          example: "A beautiful high-resolution photograph of a sunset over the mountain range."

